version: '3.1'

services:

  db:
    image: postgres
    #    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cypto-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000" # Map container port to the PORT environment variable
    volumes:
      - ./backend/src:/app/src
    env_file:
      # the env file inside the backend folder
      - ./backend/.env
    depends_on:
      - db
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "9200:9200" # Map container port to the PORT environment variable
    volumes:
      - ./src:/app/src
volumes:
  postgres_data: