version: '3.1'

services:

  db:
    image: postgres
    #    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cypto-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map container port to the PORT environment variable
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:root@db:5432/crypto-db
      PORT: 3000
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "9200:9200" # Map container port to the PORT environment variable
    volumes:
      - ./app/src:/app/src
volumes:
  postgres_data: